name: Build and Release Go Binary
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
env:
  GOGC: 50
  CGO_ENABLED: 0
permissions:
  contents: write # needed for creating releases
jobs:
  build:
    runs-on: arc-runner-set-luma-adsb
    strategy:
      matrix:
        os: ['linux']
        arch: ['arm64']
        binary: ['luma-adsb']
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get all tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: |
          go get ./...
      - name: Determine build variables
        id: vars
        run: |
          VERSION=${GITHUB_REF_NAME}
          if [[ "$VERSION" == "" ]]; then
            VERSION="dev"
          fi
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          export GOFLAGS="-trimpath"
          mkdir -p ${{ matrix.arch }}-${{ matrix.os }}
          go build -v -ldflags "-s -w -extldflags -static \
            -X 'main.Version=${{ steps.vars.outputs.version }}' \
            -X 'main.Commit=${{ steps.vars.outputs.commit }}' \
            -buildid=${{ steps.vars.outputs.version }}.${{ steps.vars.outputs.commit }} \
          " -o ${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.binary }} ./cmd/${{ matrix.binary }}
      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.binary }}
          path: |
            ${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.binary }}
  release:
    runs-on: arc-runner-set-luma-adsb
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download arm64-linux-luma-adsb
        uses: actions/download-artifact@v4
        with:
          name: binary-arm64-linux-luma-adsb
          path: artifacts/arm64-linux
      - name: rename luma-adsb for arm64-linux
        run: mv artifacts/arm64-linux/arm64-linux-luma-adsb artifacts/arm64-linux/luma-adsb
      - name: tar arm64-Linux
        run: tar -czvf ../luma-adsb-${{ github.ref_name }}-arm64-linux.tar.gz luma-adsb
        working-directory: artifacts/arm64-linux
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: artifacts/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
